name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GOMAXPROCS: 4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install Go dependencies
        run: make install

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2

      - name: Run Workflowcheck
        run: |
          go install go.temporal.io/sdk/contrib/tools/workflowcheck@latest
          make lint-workflows

      - name: Run tests
        run: make test
